"""Definición centralizada de logros del Mundo Escolar.

Cada logro tiene: id, nombre, descripción, tipo, enlace, requisito y color.
Tipo puede ser "porcentaje", "acción" o "general".
"""

LOGROS = [
    # --- Por porcentaje de materia ---
    {"id": "lectura_25", "nombre": "Iniciando el Viaje", "desc": "25% en Lectura.",
     "tipo": "porcentaje", "link": "Lectura y Escritura", "req": 0.25, "color": "#CD7F32"},
    {"id": "ajedrez_25", "nombre": "Peón Valiente", "desc": "25% en Ajedrez.",
     "tipo": "porcentaje", "link": "Ajedrez", "req": 0.25, "color": "#CD7F32"},
    {"id": "computacion_25", "nombre": "Primeros Clics", "desc": "25% en Computación.",
     "tipo": "porcentaje", "link": "Computación", "req": 0.25, "color": "#CD7F32"},
    {"id": "robotica_25", "nombre": "Pequeño Ingeniero", "desc": "25% en Robótica.",
     "tipo": "porcentaje", "link": "Robotica", "req": 0.25, "color": "#CD7F32"},
    {"id": "dibujo_25", "nombre": "Trazos Iniciales", "desc": "25% en Dibujo.",
     "tipo": "porcentaje", "link": "Dibujo", "req": 0.25, "color": "#CD7F32"},
    {"id": "lectura_60", "nombre": "Lector Avanzado", "desc": "60% en Lectura.",
     "tipo": "porcentaje", "link": "Lectura y Escritura", "req": 0.60, "color": "#C0C0C0"},
    {"id": "ajedrez_60", "nombre": "Estratega Real", "desc": "60% en Ajedrez.",
     "tipo": "porcentaje", "link": "Ajedrez", "req": 0.60, "color": "#C0C0C0"},
    {"id": "computacion_60", "nombre": "Usuario Pro", "desc": "60% en Computación.",
     "tipo": "porcentaje", "link": "Computación", "req": 0.60, "color": "#C0C0C0"},
    {"id": "robotica_60", "nombre": "Maestro de Cables", "desc": "60% en Robótica.",
     "tipo": "porcentaje", "link": "Robotica", "req": 0.60, "color": "#C0C0C0"},
    {"id": "dibujo_60", "nombre": "Artista en Marcha", "desc": "60% en Dibujo.",
     "tipo": "porcentaje", "link": "Dibujo", "req": 0.60, "color": "#C0C0C0"},
    {"id": "lectura_100", "nombre": "Maestro Lector", "desc": "100% Lectura.",
     "tipo": "porcentaje", "link": "Lectura y Escritura", "req": 1.0, "color": "#FFD700"},
    {"id": "ajedrez_100", "nombre": "Gran Maestro", "desc": "100% Ajedrez.",
     "tipo": "porcentaje", "link": "Ajedrez", "req": 1.0, "color": "#FFD700"},
    {"id": "computacion_100", "nombre": "Genio Tech", "desc": "100% Computación.",
     "tipo": "porcentaje", "link": "Computación", "req": 1.0, "color": "#FFD700"},
    {"id": "robotica_100", "nombre": "Experto Robótico", "desc": "100% Robótica.",
     "tipo": "porcentaje", "link": "Robotica", "req": 1.0, "color": "#FFD700"},
    {"id": "dibujo_100", "nombre": "Pintor Supremo", "desc": "100% Dibujo.",
     "tipo": "porcentaje", "link": "Dibujo", "req": 1.0, "color": "#FFD700"},
    # --- Generales ---
    {"id": "general_3", "nombre": "Trío Dinámico", "desc": "3 materias al 100%.",
     "tipo": "general", "link": "General_3", "req": 1.0, "color": "#FF3D00"},
    {"id": "general_todas", "nombre": "Explorador Total", "desc": "Todas las materias.",
     "tipo": "general", "link": "General_Todas", "req": 1.0, "color": "#00BFA5"},
    # --- Robótica: Misiones ---
    {"id": "robotica_partes", "nombre": "Ingeniero de Partes", "desc": "Identifica las piezas del robot.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00E5FF"},
    {"id": "robotica_emparejar", "nombre": "Sincronizador Pro", "desc": "Conecta componentes con su función.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00E5FF"},
    {"id": "robotica_programacion", "nombre": "Gran Programador", "desc": "Completa el desafío de navegación.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00E5FF"},
    # --- Ajedrez: Rangos de IA ---
    {"id": "ajedrez_hierro", "nombre": "Rango: Hierro", "desc": "Derrota a la IA nivel Hierro.",
     "tipo": "accion", "link": "", "req": 0, "color": "#B0BEC5"},
    {"id": "ajedrez_bronce", "nombre": "Rango: Bronce", "desc": "Derrota a la IA nivel Bronce.",
     "tipo": "accion", "link": "", "req": 0, "color": "#CD7F32"},
    {"id": "ajedrez_plata", "nombre": "Rango: Plata", "desc": "Derrota a la IA nivel Plata.",
     "tipo": "accion", "link": "", "req": 0, "color": "#E0E0E0"},
    {"id": "ajedrez_oro", "nombre": "Rango: Oro", "desc": "Derrota a la IA nivel Oro.",
     "tipo": "accion", "link": "", "req": 0, "color": "#FFD700"},
    {"id": "ajedrez_diamante", "nombre": "Rango: Diamante", "desc": "Derrota a la IA nivel Diamante.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00D4FF"},
    {"id": "ajedrez_maestro", "nombre": "Rango: Maestro", "desc": "Derrota a la IA nivel Maestro.",
     "tipo": "accion", "link": "", "req": 0, "color": "#A349A4"},
    {"id": "ajedrez_gran_maestro", "nombre": "Rango: Gran Maestro", "desc": "Derrota a la IA nivel Gran Maestro.",
     "tipo": "accion", "link": "", "req": 0, "color": "#FF4500"},
    {"id": "ajedrez_élite", "nombre": "Rango: Élite", "desc": "Derrota a la IA nivel Élite.",
     "tipo": "accion", "link": "", "req": 0, "color": "#FF00FF"},
    {"id": "ajedrez_galáctico", "nombre": "Rango: Galáctico", "desc": "Derrota a la IA nivel Galáctico.",
     "tipo": "accion", "link": "", "req": 0, "color": "#483D8B"},
    {"id": "ajedrez_estelar", "nombre": "Rango: Estelar", "desc": "Derrota a la IA nivel Estelar.",
     "tipo": "accion", "link": "", "req": 0, "color": "#FFFACD"},
    {"id": "ajedrez_solar", "nombre": "Rango: Solar", "desc": "Derrota a la IA nivel Solar.",
     "tipo": "accion", "link": "", "req": 0, "color": "#FFA500"},
    {"id": "ajedrez_místico", "nombre": "Rango: Místico", "desc": "Derrota a la IA nivel Místico.",
     "tipo": "accion", "link": "", "req": 0, "color": "#9370DB"},
    # --- Computación: Bibliotecas ---
    {"id": "computacion_principito", "nombre": "Pequeño Escritor", "desc": "Escribe la historia del Principito.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00FFFF"},
    {"id": "computacion_don_quijote", "nombre": "Caballero del Teclado", "desc": "Escribe las aventuras de Don Quijote.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00FFFF"},
    {"id": "computacion_los_tres_cerditos", "nombre": "Constructor de Palabras", "desc": "Completa el cuento de los Cerditos.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00FFFF"},
    {"id": "computacion_pinocho", "nombre": "Corazón de Madera", "desc": "Escribe la historia de Pinocho.",
     "tipo": "accion", "link": "", "req": 0, "color": "#00FFFF"},
    # --- Lenguaje y Lectura ---
    {"id": "lenguaje_nivel_1", "nombre": "Detective de Letras", "desc": "Completa Detective de Sonidos.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lenguaje_nivel_2", "nombre": "Constructor de Palabras", "desc": "Termina el juego Constructor.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lenguaje_nivel_3", "nombre": "Corredor de Letras", "desc": "Completa Carrera de Letras.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lenguaje_nivel_4", "nombre": "Escritor Rápido", "desc": "Finaliza Escribe Palabras.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lenguaje_nivel_5", "nombre": "Rimas en Acción", "desc": "Gana Rimas Divertidas.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lenguaje_nivel_6", "nombre": "Ordena Letras", "desc": "Domina Ordena Letras.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lenguaje_nivel_7", "nombre": "Lector Vidente", "desc": "Completa Lee y Encuentra.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lenguaje_nivel_8", "nombre": "Sopa de Lectura", "desc": "Encuentra todas las palabras en Sopa de Letras.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    # --- Lectura y Escritura ---
    {"id": "lectura_mision_1", "nombre": "Detective de Letras", "desc": "Completa el primer nivel de retos.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lectura_mision_2", "nombre": "Escritor Veloz", "desc": "Supera los desafíos de escritura.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
    {"id": "lectura_mision_3", "nombre": "Maestro del Lenguaje", "desc": "Completa todas las misiones de lectura.",
     "tipo": "accion", "link": "", "req": 0, "color": "#8D6E63"},
]

# Mensajes al desbloquear (id -> título para messagebox)
MENSAJES_LOGRO = {logro["id"]: logro["nombre"] for logro in LOGROS}
