"""Configuración del módulo config."""

LESSONS = {
    "1": {
        "titulo": "MOVIMIENTOS",
        "icono": "♟️",
        "desc": "El baile de las piezas",
        "subsecciones": ["peon", "caballo", "alfil", "torre", "dama", "rey"],
        "data": {
            "peon": [
                "EL PEÓN:",
                "Camina un paso adelante.",
                "En su primer turno,",
                "¡puede saltar dos!",
                "Descripción: El peón es la pieza",
                "más numerosa y la única que",
                "promociona al final.",
                "Tips: El peón es fuerte en grupo, ",
                "pero vulnerable solo.",
                "Tips: El peón es la columna vertebral de tu ejército. ",
                "Úsalos para controlar el centro y proteger a tus piezas más valiosas.",
                "Recuerda: El peón solo puede avanzar hacia adelante, y captura en diagonal.",
            ],
            "caballo": [
                "EL CABALLO:",
                "Salta en forma de 'L'.",
                "Es la única pieza que",
                "puede saltar sobre otras.",
                "",
                "Descripción: El caballo es",
                "impredecible, ideal para",
                "ataques sorpresa. ¡Domina el",
                "arte del salto!",
                "Tips: El caballo es fuerte en posiciones cerradas.",
                "Colócalo cerca del centro para maximizar su alcance.",
                "Recuerda: El caballo solo puede saltar sobre casillas vacías.",
            ],
            "alfil": [
                "EL ALFIL:",
                "Se desliza por las diagonals de su color.",
                "¡Vuela como el viento!",
                "",
                "Descripción: El alfil es un maestro de las diagonales.",
                "Tips: El alfil es fuerte en posiciones abiertas, donde puede controlar largas diagonales.",
                "Recuerda: El alfil solo puede moverse y capturar en su color de casilla.",
                "Consejo: Ten cuidado con los alfiles enemigos, pueden atacar desde lejos sin ser vistos.",
            ],
            "torre": [
                "LA TORRE:",
                "Se mueve en líneas rectas: filas y columnas.",
                "¡Es un muro sólido!",
                "",
                "Descripción: La torre es poderosa en el final del juego.",
                "Tips: La torre es fuerte en posiciones abiertas, especialmente en la séptima fila del oponente.",
                "Recuerda: La torre solo puede moverse y capturar en la misma fila o columna, sin piezas intermedias.",
                "Consejo: Las torres trabajan mejor en conjunto. ¡Dales apoyo mutuo!",
            ],
            "dama": [
                "LA DAMA:",
                "¡La más poderosa!",
                "Se mueve como Torre y Alfil a la vez.",
                "",
                "Descripción: La dama es la reina del tablero.",
                "Tips: La dama es fuerte en casi todas las posiciones, ",
                "pero ten cuidado de no exponerla demasiado temprano.",
                "Recuerda: La dama puede moverse y capturar en cualquier dirección, ",
                "pero no puede saltar sobre otras piezas.",
                "Consejo: La dama es una pieza de ataque versátil, ",
                "pero no subestimes el poder de las piezas menores para protegerla.",
            ],
            "rey": [
                "EL REY:",
                "Es el más importante.",
                "Mueve un paso hacia cualquier dirección.",
                "",
                "Descripción: El rey es el centro del juego. ¡Protégelo!",
                "Tips: El rey es fuerte en el final del juego, donde puede participar activamente.",
                "Recuerda: El rey solo puede moverse un paso en cualquier dirección, ",
                "y no puede moverse a una casilla atacada por el enemigo.",
                "Consejo: Mantén a tu rey seguro durante la apertura y el medio juego, ",
                "y luego actívalo en el final para ayudar a ganar la partida.",
            ],
        },
    },
    "2": {
        "titulo": "CAPTURAS",
        "icono": "⚔️",
        "desc": "¡Ocupa su lugar!",
        "subsecciones": ["peon", "caballo", "alfil", "torre", "dama", "rey"],
        "data": {
            "peon": [
                "CAPTURA PEÓN:",
                "El peon come diferente.",
                "Solo captura en diagonal un paso adelante.",
                "¡Cuidado con los peones enemigos!",
                "Tips: El peón es una amenaza silenciosa. ",
                "Tips: Captura las piezas siguiendo las flechas verdes.",
                "¡Cada peón tiene su propio objetivo!",
                "Siempre revisa las diagonales antes de mover tus piezas.",
                "Recuerda: El peón solo puede capturar piezas que estén en diagonal un paso adelante.",
                "Consejo: Los peones pueden ser muy peligrosos si logran avanzar, ",
                "así que mantén un ojo en su progreso y bloquea su avance cuando sea necesario.",
            ],
            "caballo": [
                "CAPTURA CABALLO:",
                "Salta y cae sobre la pieza enemiga."
                "¡Ataque sorpresa!"
                "Tips: El caballo es excelente para capturar piezas que están protegidas por otras, ",
                "gracias a su capacidad de salto.",
                "Recuerda: El caballo solo puede capturar piezas que estén en su destino de movimiento en forma de 'L'.",
                "Consejo: Usa el caballo para atacar piezas valiosas del oponente, ",
            ],
            "alfil": [
                "CAPTURA ALFIL:",
                "Sigue su diagonal hasta encontrar al enemigo.",
                "Tips: El alfil es fuerte en posiciones abiertas, donde puede controlar largas diagonales.",
                "Recuerda: El alfil solo puede capturar piezas que estén en su color de casilla.",
                "Consejo: El alfil puede ser una amenaza a larga distancia, así que ten cuidado con sus ataques desde lejos.",
                "Recuerda: El alfil no puede saltar sobre otras piezas, ",
                "así que asegúrate de que su camino esté despejado para capturar.",
                "Consejo: Los alfiles trabajan bien en conjunto, ",
                "especialmente si controlan diagonales opuestas. ¡Dales apoyo mutuo para capturar piezas enemigas!",
            ],
            "torre": [
                "CAPTURA TORRE:",
                "Lanza su torre en línea recta hasta impactar.",
                "Tips: La torre es fuerte en posiciones abiertas, especialmente en la séptima fila del oponente.",
                "Recuerda: La torre solo puede capturar piezas que estén en la misma fila o columna, sin piezas intermedias.",
                "Consejo: La torre es una pieza de ataque poderosa, ",
                "pero asegúrate de que esté bien protegida para evitar contraataques.",
                "Recuerda: La torre no puede saltar sobre otras piezas, ",
                "así que asegúrate de que su camino esté despejado para capturar.",
                "Consejo: Las torres trabajan mejor en conjunto. ¡Dales apoyo mutuo para capturar piezas enemigas!",
            ],
            "dama": ["CAPTURA DAMA:", "Busca a su presa en cualquier dirección."],
            "rey": [
                "CAPTURA REY:",
                "El Rey captura igual que como se mueve: ¡Un paso a la vez!",
                "Tips: El rey es fuerte en el final del juego, donde puede participar activamente.",
                "Recuerda: El rey solo puede capturar piezas que estén en su destino de movimiento de un paso en cualquier dirección,",
                " y no puede capturar piezas que estén protegidas por otras.",
                "Consejo: El rey es una pieza de ataque subestimada en el final del juego.",
                "¡No dudes en usarlo para capturar piezas enemigas cuando sea seguro hacerlo!",
            ],
        },
    },
    "3": {
        "titulo": "ESPECIALES",
        "icono": "✨",
        "desc": "Trucos mágicos",
        "subsecciones": ["enroque", "promocion", "paso"],
        "data": {
            "enroque": [
                "EL ENROQUE:",
                "El Rey y la Torre se unen.",
                "¡Es el escudo real!",
                "Tips: El enroque es una jugada defensiva clave para proteger a tu rey y conectar tus torres.",
                "Recuerda: El enroque solo es posible si ni el rey ni la torre han movido antes, ",
                "no hay piezas entre ellos, y el rey no está en jaque ni pasa por casillas atacadas.",
                "Consejo: El enroque puede ser una herramienta estratégica para mejorar la seguridad ",
                "de tu rey y activar tus torres.",
                "¡No lo subestimes!",
            ],
            "promocion": [
                "LA PROMOCIÓN:",
                "Un peón llega al final y se transforma.",
                "¡Elige tu pieza poderosa!",
                "Tips: La promoción es una oportunidad para obtener una pieza poderosa, ",
                "así que planifica tu avance de peones con cuidado.",
                "Recuerda: Un peón que alcanza la fila opuesta puede promocionar a dama, torre, ",
                "alfil o caballo, según tu elección.",
                "Consejo: La mayoría de las veces, promocionar a dama es la mejor opción, ",
                "pero en algunas situaciones tácticas, promocionar a torre, alfil o caballo puede ser más beneficioso. ",
                "¡Evalúa la posición antes de decidir!",
            ],
            "paso": [
                "PEÓN AL PASO:",
                "Captura un peón que intentó esquivarte.",
                "¡El truco del fantasma!",
                "Tips: El peón al paso es una oportunidad táctica para capturar un peón enemigo que"
                " intenta avanzar dos casillas desde su posición inicial.",
                "Recuerda: El peón al paso solo puede realizarse inmediatamente después de que el peón enemigo"
                " haya avanzado dos casillas desde su posición inicial, y solo puede ser capturado por un peón adyacente.",
                "Consejo: El peón al paso puede ser una herramienta poderosa para interrumpir el avance de los peones ",
                "enemigos y ganar control del centro del tablero. ¡Mantente atento a esta jugada especial!",
            ],
        },
    },
    "4": {
        "titulo": "JAQUE",
        "icono": "👑",
        "desc": "¡Rey en peligro!",
        "subsecciones": ["jaque", "jaque_mate"],
        "data": {
            "jaque": [
                "¡JAQUE!",
                "Tu Rey está amenazado.",
                "Usa las 3 'C': ESCAPAR, CUBRIR o CAPTURAR.",
                "Tips: El jaque es una amenaza directa al rey. ",
                "Siempre busca formas de escapar, cubrir o capturar para salir del jaque.",
                "Recuerda: El jaque es una amenaza directa al rey. ",
                "Para salir del jaque, debes mover el rey a una casilla segura, ",
                "cubrir al rey con otra pieza o capturar la pieza atacante.",
                "Consejo: El jaque puede ser una oportunidad para ganar ventaja material o posicional, ",
                "así que busca formas de convertir un jaque en una jugada favorable para ti. ",
                "¡Pero ten cuidado de no caer en jaques dobles o trampas tácticas!",
            ],
            "jaque_mate": [
                "¡JAQUE MATE!",
                "El objetivo final.",
                "¡Victoria definitiva!",
                "Tips: El jaque mate es el objetivo final del juego. ",
                "Busca formas de crear amenazas de jaque mate para ganar la partida.",
                "Recuerda: El jaque mate es el objetivo final del juego. ",
                "Ocurre cuando el rey está en jaque y no tiene ninguna jugada legal para escapar, cubrir o capturar la pieza atacante.",
                "Consejo: El jaque mate puede ser una herramienta poderosa para ganar la partida, ",
                "así que busca formas de crear amenazas de jaque mate para ganar la partida. ",
                "¡Pero ten cuidado de no caer en jaques dobles o trampas tácticas",
            ],
        },
    },
    "5": {
        "titulo": "REGLAS",
        "icono": "📜",
        "desc": "Tablas y Clavadas",
        "subsecciones": ["ahogado", "tablas", "insuficiencia_material", "clavada"],
        "data": {
            "ahogado": [
                "REY AHOGADO:",
                "El rey está atrapado en h1 sin jaque.",
                "La dama negra en g5 cierra todas las salidas.",
                "No hay movimiento legal disponible.",
                "Esta posición es un empate automático.",
                "Tips: El rey ahogado es una situación de empate donde el rey no está en jaque pero no tiene movimientos legales disponibles.",
                "Recuerda: El rey ahogado es una situación de empate donde el rey no está en jaque pero ",
                "no tiene movimientos legales disponibles.",
                "Consejo: El rey ahogado puede ser una herramienta táctica para salvar una partida perdida, ",
                "así que busca formas de crear situaciones de ahogado para evitar la derrota. ",
                "¡Pero ten cuidado de no caer en trampas tácticas que te lleven a un ahogado sin querer!",
            ],
            "tablas": [
                "TABLAS:",
                "Solo quedan los dos reyes en el tablero.",
                "Eso significa que nadie puede forzar la victoria.",
                "Las tablas pueden ser útiles si prefieres no arriesgarte.",
                "En algunas partidas, conservar el empate es la mejor decisión.",
                "Tips: Las tablas son un resultado de empate donde ninguno de los jugadores puede forzar una victoria.",
                "Recuerda: Las tablas pueden ocurrir por acuerdo mutuo, repetición de movimientos,",
                " falta de material para dar mate, o por la regla de los 50 movimientos sin captura ni movimiento de peón.",
                "Consejo: Las tablas pueden ser una herramienta estratégica para salvar una partida",
                " perdida o asegurar un resultado favorable, así que busca formas de crear ",
                "situaciones de tablas cuando sea necesario. ",
                "¡Pero ten cuidado de no caer en trampas tácticas que te lleven a tablas sin querer!",
            ],
            "insuficiencia_material": [
                "INSUFICIENCIA:",
                "Aquí solo quedan rey y caballo contra rey.",
                "No hay material suficiente para dar mate.",
                "Otras situaciones similares son rey contra rey,",
                "rey contra rey y alfil o rey contra rey y caballo.",
                "Para evitarlo, busca cambiar a piezas más fuertes antes del final.",
                "Tips: La insuficiencia de material es una situación de empate donde ninguno de"
                "los jugadores tiene suficiente material para dar mate.",
                "Recuerda: La insuficiencia de material es una situación de empate donde ninguno ",
                "de los jugadores tiene suficiente material para dar mate, como rey contra rey, ",
                "rey contra rey y alfil, rey contra rey y caballo, o rey y caballo contra rey.",
                "Consejo: La insuficiencia de material puede ser una herramienta táctica para salvar ",
                "una partida perdida, así que busca formas de crear situaciones de insuficiencia de material para evitar la derrota. ",
                "¡Pero ten cuidado de no caer en trampas tácticas que te lleven a insuficiencia de material sin querer!",
            ],
            "clavada": [
                "LA CLAVADA:",
                "Es una amenaza en línea donde una pieza queda inmovilizada",
                "para proteger a otra pieza más valiosa, generalmente el rey.",
                "Surge cuando un alfil, torre o dama se coloca en la misma fila,",
                "columna o diagonal que une la pieza clavada con el rey.",
                "Consiste en forzar al oponente a no mover esa pieza",
                "porque al hacerlo perdería la pieza de mayor valor o quedaría",
                "su rey expuesto a un ataque decisivo.",
                "Tip: Evita la clavada manteniendo tus piezas bien defendidas",
                "y no alineándolas frente a tu rey.",
                "Defensa: bloquea la línea, mueve tu rey o cambia la pieza atacante.",
                "Recuerda: una clavada puede decidir una partida si no la ves a tiempo.",
                "Consejo: La clavada es una herramienta táctica poderosa para inmovilizar piezas enemigas y ganar ventaja material, ",
                "así que busca formas de crear clavadas para debilitar la posición de tu oponente. ",
                "¡Pero ten cuidado de no caer en clavadas tú mismo! Mantén tus piezas protegidas y ",
                "evita alinearlas frente a tu rey para minimizar el riesgo de ser clavado.",
            ],
        },
    },
}